import Image from 'next/image';
import Link from 'next/link';
import SiteFooter from './SiteFooter';
import SectionHeading from './SectionHeading';
import { eventTypes, reviews, stats } from './site-data';

const gallery = ['/assets/gallery/g27.jpeg', '/assets/gallery/g12.jpeg', '/assets/gallery/g19.jpeg', '/assets/gallery/g15.jpeg'];

export default function HomePage() {
  return <main><section className="relative isolate min-h-svh overflow-hidden bg-ink text-white"><div className="absolute inset-0 -z-20"><video autoPlay muted loop playsInline poster="/assets/hero/hero-1.jpg" className="size-full object-cover"><source src="/assets/hero-video-optimized.mp4" type="video/mp4" /></video></div><div className="absolute inset-0 -z-10 bg-gradient-to-b from-ink/65 via-transparent to-ink" /><div className="page-shell flex min-h-svh items-end pb-20 pt-32 sm:pb-28"><div><p className="eyebrow">For our future family</p><h1 className="display mt-5 max-w-4xl text-5xl leading-[.92] sm:text-7xl lg:text-8xl">Let&apos;s create<br />magical memories<br />together<span className="text-gold">.</span></h1><p className="mt-7 text-sm uppercase tracking-[.18em] text-stone-200">Premium event planning · Bardoli, Gujarat</p><Link href="#about" className="mt-10 inline-flex border-b border-gold pb-2 text-sm font-semibold uppercase tracking-[.18em] text-gold-light">Discover Utsah</Link></div></div></section>
    <section id="about" className="bg-paper py-20 sm:py-28"><div className="page-shell"><div className="grid gap-px bg-stone-300 sm:grid-cols-4">{stats.map(([value, label]) => <div key={label} className="bg-paper px-5 py-7 text-center"><p className="display text-4xl text-gold">{value}</p><p className="mt-2 text-xs font-bold uppercase tracking-[.14em] text-stone-600">{label}</p></div>)}</div><div className="mt-20 grid items-center gap-12 lg:grid-cols-[.85fr_1.15fr]"><SectionHeading eyebrow="Who we are" title="Celebrations with soul" /><div className="max-w-2xl text-lg leading-8 text-stone-700"><p>UTSAH is a comprehensive planning and coordination service for customised events and weddings. We design, plan and manage every project from first idea to final farewell.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/events" className="border border-stone-400 px-5 py-3 text-sm font-semibold hover:border-gold hover:text-gold">Premium event experiences</Link><Link href="/about" className="border border-stone-400 px-5 py-3 text-sm font-semibold hover:border-gold hover:text-gold">Meet our team</Link></div></div></div></div></section>
    <section className="bg-ink py-20 text-white sm:py-28"><div className="page-shell"><SectionHeading eyebrow="What we create" title="Moments made personal" /><div className="mt-12 grid gap-5 lg:grid-cols-3">{eventTypes.map((event) => <Link key={event.href} href={event.href} className="group relative min-h-105 overflow-hidden bg-stone-900"><Image src={event.image} alt="" fill sizes="(max-width: 1024px) 100vw, 33vw" className="object-cover opacity-65 transition duration-700 group-hover:scale-105 group-hover:opacity-45" /><div className="absolute inset-0 bg-gradient-to-t from-ink via-ink/15 to-transparent" /><div className="absolute inset-x-0 bottom-0 p-7"><h3 className="display text-3xl">{event.title}</h3><p className="mt-3 max-w-sm text-sm leading-6 text-stone-200">{event.text}</p><span className="mt-5 inline-block text-xs font-bold uppercase tracking-[.2em] text-gold-light">Explore</span></div></Link>)}</div></div></section>
    <section className="bg-paper py-20 sm:py-28"><div className="page-shell"><SectionHeading eyebrow="Selected work" title="Memory, made visible" centered /><div className="mt-12 grid grid-cols-2 gap-3 sm:grid-cols-4">{gallery.map((src, index) => <div key={src} className={index === 0 ? 'relative col-span-2 row-span-2 min-h-72' : 'relative min-h-40'}><Image src={src} alt="Utsah event celebration" fill sizes="(max-width: 640px) 50vw, 25vw" className="object-cover" /></div>)}</div><div className="mt-10 text-center"><Link href="/memories" className="inline-flex border-b border-stone-900 pb-2 text-sm font-bold uppercase tracking-[.18em]">View all memories</Link></div></div></section>
    <section className="bg-stone-100 py-20 sm:py-28"><div className="page-shell"><SectionHeading eyebrow="Google reviews" title="What clients say" centered /><div className="mt-12 grid gap-5 md:grid-cols-3">{reviews.map(([name, quote]) => <figure key={name} className="border border-stone-200 bg-white p-7"><div className="text-gold">★★★★★</div><blockquote className="mt-5 leading-7 text-stone-700">“{quote}”</blockquote><figcaption className="mt-6 text-sm font-bold">{name}</figcaption></figure>)}</div></div></section>
    <section className="bg-gold py-20 text-center text-ink"><div className="page-shell"><p className="text-xs font-bold uppercase tracking-[.24em]">Start a conversation</p><h2 className="display mt-4 text-4xl sm:text-6xl">Let&apos;s create lasting memories.</h2><Link href="/contact" className="mt-8 inline-block bg-ink px-6 py-4 text-sm font-bold uppercase tracking-[.18em] text-white hover:bg-stone-800">Contact Utsah</Link></div></section><SiteFooter /></main>;
}
