// Generated by scripts/make-intro.py with the strokes it has to follow.
// Kept apart from strokes.ts so client code can import it without pulling
// in the segment table.
//
// ms from first paint. IntroOverlay passes these to CSS, app/layout.tsx
// tears down at INTRO_TOTAL, and components/motion/reveal.tsx releases
// afterIntro content at CURTAIN_AT.
export const WRITE_END = 2650;
export const SETTLE_AT = 2650;
export const SETTLE_MS = 200;
export const EXIT_AT = 2850;
export const LIFT_MS = 380;
export const CURTAIN_AT = 2930;
export const CURTAIN_MS = 650;
export const LAYER_STAGGER = 90;
export const INTRO_TOTAL = 3760;
